### PR TITLE
add version 1.95 support

### PR DESCRIPTION
**Pull request by azazellochg**
Old 1.1.5-s2 version deprecated.

### CODE REVIEW

**Comment by azazellochg** [comment]
Also, installation not tested..

**Comment by pconesa** [comment]
@azazellochg where can I get the resmap-1.95.tgz

**Comment by pconesa** [comment]
I think I found it: https://sourceforge.net/projects/resmap-latest/files/Releases/TarBalls/
This is python3 code? 
Did you manually installed it?

**Comment by azazellochg** [comment]
Not the tarballs but in executable folder, you can find binaries, you will
also need Cuda lib file matching your gpu. I didn't make tgz

**Comment by azazellochg** [comment]
Python 3 only needed to compile it, so don't worry about it

**Comment by pconesa** [comment]
But then, installation from scipion cannot be done...right?

**Comment by azazellochg** [comment]
No, not yet. That is what I said

**Comment by azazellochg** [comment]
@pconesa feel free to upload https://mega.nz/#!R5RAwSRb!qUbgzZ8WjYC3t_jpPaeQqbZQpM0leudZAf3SxDhADQw to the server and then you can merge this PR

**Pull request merged**
